ALTER TABLE distribuidor
ADD COLUMN IF NOT EXISTS latitud DECIMAL(10,7)
CHECK (latitud BETWEEN -90 AND 90);

ALTER TABLE distribuidor
ADD COLUMN IF NOT EXISTS longitud DECIMAL(10,7)
CHECK (longitud BETWEEN -180 AND 180);
